"""
Django settings for pytimeline project.

Generated by 'django-admin startproject' using Django 4.1.7.

Dev enviroment settings
"""

from .base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j+^*5e*dp&=7o=*5=5=xhcr9i!r99_xz25!)lwr08kk_9hu%o!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = DEBUG
