# Generated by Django 4.1.7 on 2024-02-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0002_create_initial_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePlayerGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.game')),
            ],
            bases=('engine.game',),
        ),
    ]
