# Generated by Django 4.1.7 on 2023-10-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('deck_size', models.PositiveIntegerField(default=60)),
                ('initial_hand_size', models.PositiveIntegerField(default=5)),
                ('turn', models.PositiveIntegerField(default=0)),
                ('n_players', models.PositiveSmallIntegerField(default=3)),
                ('deck', models.ManyToManyField(to='multiplayer.card')),
                ('discard_deck', models.ManyToManyField(related_name='discard_deck', to='multiplayer.card')),
                ('last_correct_card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_correct_in_games', to='multiplayer.card')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='multiplayer.card')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cards', models.ManyToManyField(to='multiplayer.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='multiplayer.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='timeline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='multiplayer.timeline'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('name', 'game'), name='unique_username_per_game'),
        ),
    ]
