# Generated by Django 4.1 on 2023-03-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_size', models.PositiveIntegerField(default=60)),
                ('initial_hand_size', models.PositiveIntegerField(default=5)),
                ('current', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
