# Generated by Django 4.1 on 2023-03-24 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_size', models.PositiveIntegerField(default=60)),
                ('initial_hand_size', models.PositiveIntegerField(default=5)),
                ('current', models.PositiveIntegerField(default=0)),
                ('deck', models.ManyToManyField(to='engine.card')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='engine.card')),
            ],
       ),
        migrations.AddField(
            model_name='game',
            name='timeline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='engine.timeline'),
        ),
    ]
