# Generated by Django 4.1 on 2023-03-24 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_create_initial_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timeline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='engine.timeline'),
        ),
    ]
