# Generated by Django 4.1.7 on 2023-10-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_create_initial_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current',
        ),
        migrations.RemoveField(
            model_name='game',
            name='deck_size',
        ),
        migrations.RemoveField(
            model_name='game',
            name='initial_hand_size',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='cards',
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='juego', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateTimeField(verbose_name='fecha evento'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='engine.timeline'),
        ),
    ]
