# Generated by Django 4.1 on 2023-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_game_timeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current',
            new_name='turn',
        ),
        migrations.AddField(
            model_name='game',
            name='n_players',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
