# Generated by Django 4.1 on 2023-03-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_populate_initial_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.ManyToManyField(to='engine.card'),
        ),
    ]
