# Generated by Django 4.1 on 2023-03-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_rename_current_game_turn_game_n_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_played_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_in_games', to='engine.card'),
        ),
    ]
