# Generated by Django 4.1 on 2023-03-25 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_game_last_played_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_played_card',
        ),
        migrations.AddField(
            model_name='game',
            name='last_correct_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_correct_in_games', to='engine.card'),
        ),
    ]
