# Generated by Django 4.1 on 2023-03-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_remove_game_last_played_card_game_last_correct_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='Perros', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='n_players',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
