# Generated by Django 4.1 on 2023-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_game_discard_deck'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('name', 'game'), name='unique_username_per_game'),
        ),
    ]
